/**
 * Every named TRREB community currently appearing in active Toronto listings,
 * mapped to its exact district code (Property.city value). Generated from
 * live synced data (Property.neighbourhood, sourced from AMPRE's own
 * CityRegion field), not transcribed from a boundary map — that avoids the
 * exact failure mode this file exists to prevent: a wrong community-to-code
 * guess silently returning listings from the wrong part of the city.
 *
 * Verified 1:1 - none of these 144 names appears under more than
 * one code, so a flat name -> code lookup is safe. Former-borough names
 * (Scarborough, Etobicoke, York, East York) are deliberately NOT here: they
 * span multiple codes each, and where their historical boundaries fall on
 * today's C/E/W district lines is genuinely ambiguous - unlike North York
 * (lib/seo/gta-cities.ts), no single verifiable source resolves that split,
 * so guessing it would risk exactly what this file avoids for everything
 * else. Regenerate by re-running the GROUP BY query in this file's history
 * if the synced community list changes.
 */
export interface TorontoCommunity {
  name: string
  /** Exact Property.city value, e.g. "Toronto C12". */
  code: string
}

export const TORONTO_COMMUNITIES: TorontoCommunity[] = [
  { name: "Agincourt North", code: "Toronto E07" },
  { name: "Agincourt South-Malvern West", code: "Toronto E07" },
  { name: "Alderwood", code: "Toronto W06" },
  { name: "Amesbury", code: "Toronto W04" },
  { name: "Annex", code: "Toronto C02" },
  { name: "Bathurst Manor", code: "Toronto C06" },
  { name: "Bay Street Corridor", code: "Toronto C01" },
  { name: "Bayview Village", code: "Toronto C15" },
  { name: "Bayview Woods-Steeles", code: "Toronto C15" },
  { name: "Beaumonde Heights", code: "Toronto W10" },
  { name: "Bedford Park-Nortown", code: "Toronto C04" },
  { name: "Bellwoods", code: "Toronto C01" },
  { name: "Bendale", code: "Toronto E09" },
  { name: "Birchmount", code: "Toronto E04" },
  { name: "Black Creek", code: "Toronto W05" },
  { name: "Bloor West Village", code: "Toronto W02" },
  { name: "Branson", code: "Toronto C07" },
  { name: "Briar Hill-Belgravia", code: "Toronto W04" },
  { name: "Bridle Path-Sunnybrook-York Mills", code: "Toronto C12" },
  { name: "Broadview North", code: "Toronto E03" },
  { name: "Casa Loma", code: "Toronto C02" },
  { name: "Cedarvale", code: "Toronto C03" },
  { name: "Centennial Scarborough", code: "Toronto E10" },
  { name: "Centennial-West Deane", code: "Toronto W08" },
  { name: "Chinatown", code: "Toronto C01" },
  { name: "City Centre West", code: "Toronto W08" },
  { name: "Clanton Park", code: "Toronto C06" },
  { name: "Cliffcrest", code: "Toronto E08" },
  { name: "Cliffside", code: "Toronto E06" },
  { name: "Corso Italia-Davenport", code: "Toronto W03" },
  { name: "Coxwell", code: "Toronto E01" },
  { name: "Crescent Town", code: "Toronto E03" },
  { name: "Danforth", code: "Toronto E03" },
  { name: "Danforth Village-East York", code: "Toronto E03" },
  { name: "Don Mills", code: "Toronto C13" },
  { name: "Don Valley Village", code: "Toronto C15" },
  { name: "Donalda", code: "Toronto C13" },
  { name: "Dorset Park", code: "Toronto E04" },
  { name: "Dufferin Grove", code: "Toronto C01" },
  { name: "East End-Danforth", code: "Toronto E02" },
  { name: "East York", code: "Toronto E03" },
  { name: "Eglinton", code: "Toronto C03" },
  { name: "Eglinton East", code: "Toronto E08" },
  { name: "Eglinton West", code: "Toronto W03" },
  { name: "Etobicoke West Mall", code: "Toronto W08" },
  { name: "Fairbank", code: "Toronto W03" },
  { name: "Flemingdon Park", code: "Toronto C11" },
  { name: "Forest Hill North", code: "Toronto C04" },
  { name: "Forest Hill South", code: "Toronto C03" },
  { name: "Glen Park", code: "Toronto W04" },
  { name: "Greenbrook", code: "Toronto W04" },
  { name: "Guildwood", code: "Toronto E08" },
  { name: "Henry Farm", code: "Toronto C15" },
  { name: "High Park North", code: "Toronto W02" },
  { name: "High Park-Swansea", code: "Toronto W01" },
  { name: "Highland Creek", code: "Toronto E10" },
  { name: "Hillcrest Village", code: "Toronto C15" },
  { name: "Humber Heights", code: "Toronto W09" },
  { name: "Humber Summit", code: "Toronto W05" },
  { name: "Humber Valley", code: "Toronto W08" },
  { name: "Humbermede", code: "Toronto W05" },
  { name: "Ionview", code: "Toronto E04" },
  { name: "Jane Heights", code: "Toronto W05" },
  { name: "Jones", code: "Toronto E01" },
  { name: "Junction Area", code: "Toronto W02" },
  { name: "Kennedy Park", code: "Toronto E04" },
  { name: "Kingsview Village-The Westway", code: "Toronto W09" },
  { name: "Kingsway South", code: "Toronto W08" },
  { name: "Kipling", code: "Toronto W10" },
  { name: "L'Amoreaux", code: "Toronto E05" },
  { name: "Lambton Baby Point", code: "Toronto W02" },
  { name: "Lawrence", code: "Toronto C04" },
  { name: "Lawrence Park North", code: "Toronto C04" },
  { name: "Lawrence Park South", code: "Toronto C04" },
  { name: "Leaside", code: "Toronto C11" },
  { name: "Little Italy", code: "Toronto C01" },
  { name: "Little Portugal", code: "Toronto C01" },
  { name: "Long Branch", code: "Toronto W06" },
  { name: "Lumsden", code: "Toronto E03" },
  { name: "Malvern", code: "Toronto E11" },
  { name: "Maple Leaf", code: "Toronto W04" },
  { name: "Markland Wood", code: "Toronto W08" },
  { name: "Martingrove-Richview", code: "Toronto W09" },
  { name: "Maryvale", code: "Toronto E04" },
  { name: "Milliken", code: "Toronto E07" },
  { name: "Mimico", code: "Toronto W06" },
  { name: "Moore Park", code: "Toronto C09" },
  { name: "Morningside", code: "Toronto E09" },
  { name: "Moss Park", code: "Toronto C08" },
  { name: "Mount Dennis", code: "Toronto W04" },
  { name: "Mount Olive-Silverstone-Jamestown", code: "Toronto W10" },
  { name: "Mount Pleasant East", code: "Toronto C10" },
  { name: "Mount Pleasant West", code: "Toronto C10" },
  { name: "New Toronto", code: "Toronto W06" },
  { name: "Newtonbrook East", code: "Toronto C14" },
  { name: "Newtonbrook West", code: "Toronto C07" },
  { name: "Niagara", code: "Toronto C01" },
  { name: "North Riverdale", code: "Toronto E01" },
  { name: "North St. James Town", code: "Toronto C08" },
  { name: "O'Connor-Parkview", code: "Toronto E03" },
  { name: "Oakridge", code: "Toronto E06" },
  { name: "Oakwood Village", code: "Toronto C03" },
  { name: "Old Rexdale", code: "Toronto W10" },
  { name: "Pellam Park", code: "Toronto W03" },
  { name: "Pelmo Park W4", code: "Toronto W04" },
  { name: "Pelmo Park W5", code: "Toronto W05" },
  { name: "Playter Estates-Danforth", code: "Toronto E03" },
  { name: "Pleasant View", code: "Toronto C15" },
  { name: "Queensway", code: "Toronto W07" },
  { name: "Regent Park", code: "Toronto C08" },
  { name: "Roding-CFB", code: "Toronto W05" },
  { name: "Roncesvalles", code: "Toronto W01" },
  { name: "Rosethorn", code: "Toronto W08" },
  { name: "Rouge E10", code: "Toronto E10" },
  { name: "Rouge E11", code: "Toronto E11" },
  { name: "Rustic", code: "Toronto W04" },
  { name: "Scarborough Village", code: "Toronto E08" },
  { name: "Smythe", code: "Toronto W03" },
  { name: "South Parkdale", code: "Toronto W01" },
  { name: "South Riverdale", code: "Toronto E01" },
  { name: "South St. James Town", code: "Toronto C08" },
  { name: "St. Andrew-Windfields", code: "Toronto C12" },
  { name: "St. Clair", code: "Toronto C02" },
  { name: "Steeles", code: "Toronto E05" },
  { name: "Tam O'Shanter-Sullivan", code: "Toronto E05" },
  { name: "The Beaches", code: "Toronto E02" },
  { name: "The Islands", code: "Toronto C01" },
  { name: "Thorncliffe Park", code: "Toronto C11" },
  { name: "University", code: "Toronto C01" },
  { name: "Victoria Village", code: "Toronto C13" },
  { name: "Wallace Emerson-Junction", code: "Toronto W02" },
  { name: "Waterfront Communities C1", code: "Toronto C01" },
  { name: "Waterfront Communities C8", code: "Toronto C08" },
  { name: "West Hill", code: "Toronto E10" },
  { name: "West Humber-Clairville", code: "Toronto W10" },
  { name: "Westgate", code: "Toronto C07" },
  { name: "Weston", code: "Toronto W04" },
  { name: "Willowdale East", code: "Toronto C14" },
  { name: "Willowdale West", code: "Toronto C07" },
  { name: "Woburn", code: "Toronto E09" },
  { name: "Woodbine Corridor", code: "Toronto E02" },
  { name: "Wychwood", code: "Toronto C02" },
  { name: "Yonge Corridor", code: "Toronto C08" },
  { name: "York University Heights", code: "Toronto W05" },
]
